Update run-fivetran-command.yml

diff --git a/.github/workflows/run-fivetran-command.yml b/.github/workflows/run-fivetran-command.yml
--- a/.github/workflows/run-fivetran-command.yml
+++ b/.github/workflows/run-fivetran-command.yml
@@ -25,9 +25,27 @@ jobs:
       - name: Run Fivetran Debug
         working-directory: examples/quickstart_examples/hello  
         run: |
-          echo "Running in directory: $(pwd)"
-          ls
-          echo "-----------"
-          cat connector.py
-          echo "-----------"
-          fivetran debug --acadf
+          # echo "Running in directory: $(pwd)"
+          # ls
+          # echo "-----------"
+          # cat connector.py
+          # echo "-----------"
+          # fivetran debug --acadf
+          # run: |
+          set -o pipefail
+          echo "Running Fivetran Deploy..."
+          output=$(fivetran deploy \
+            --api-key "adfadfasdf" \
+            --destination "Sample1" \
+            --connection "check_this" \
+            --configuration configuration.json \
+            --python-version "3.15" \
+            --force 2>&1)
+          exit_code=$?
+          
+          echo "$output"
+      
+          if [ $exit_code -ne 0 ]; then
+            echo "Fivetran deploy failed with exit code $exit_code"
+            exit $exit_code
+          fi
