Update run-fivetran-command.yml

diff --git a/.github/workflows/run-fivetran-command.yml b/.github/workflows/run-fivetran-command.yml
--- a/.github/workflows/run-fivetran-command.yml
+++ b/.github/workflows/run-fivetran-command.yml
@@ -27,12 +27,40 @@ jobs:
           TEST_KEY: ${{ secrets.SATVIK_API_TEST }}
         working-directory: examples/quickstart_examples/hello  
         run: |
-          echo "Starting Fivetran deployment"
           set -o pipefail
-          fivetran deploy \
-            --api-key "${TEST_KEY}" \
-            --destination "Testing" \
-            --connection "satvik_csdk_test_github_action" \
-            --python-version "3.11.11" \
-            --force 2>&1 | tee fivetran_deploy.log
-          echo "New approach"
+
+          echo "Approach 1: Starting Fivetran deploy..."
+      
+          script -q -e -c "fivetran deploy \
+            --api-key '${{ secrets.TEST_KEY }}' \
+            --destination 'Testing' \
+            --connection 'satvik_csdk_test_github_action' \
+            --python-version '3.11.11' \
+            --force" fivetran_deploy.log
+      
+          status=$?
+          cat fivetran_deploy.log
+      
+          if [ "$status" -ne 0 ]; then
+            echo "❌ Fivetran deploy failed with status $status"
+            exit $status
+          else
+            echo "✅ Fivetran deploy succeeded"
+          fi
+
+          echo "Approach 2: Starting Fivetran deploy..."
+          
+          unbuffer fivetran deploy \
+          --api-key '${{ secrets.TEST_KEY }}' \
+          --destination 'Testing' \
+          --connection 'satvik_csdk_test_github_action' \
+          --python-version '3.11.11' \
+          --force 2>&1 | tee fivetran_deploy.log
+    
+          status=${PIPESTATUS[0]}
+          cat fivetran_deploy.log
+      
+          if [ "$status" -ne 0 ]; then
+            echo "❌ Fivetran deploy failed with status $status"
+            exit $status
+          fi
